project:
  type: website
  output-dir: ./docs  # rendered html pages will be stored here
  resources:
    - interactive_lloyd/lloyd_demo_app.html

website:
  title: "Sungyeon Hong"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        menu:
          - text: Overview
            href: research.qmd
          - text: Geometry-driven hyperuniformity
            href: research/geometry-driven-hyperuniformity.qmd
          - text: Topological analysis for information flow
            href: research/topological-analysis-information-flow.qmd
          - text: Supervision
            href: research/supervision.qmd
      - text: Education
        href: education.qmd
      - text: Engagements
        href: engagements.qmd
      - text: Publications
        href: publications.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
